name: 'Dependency Review'

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday
  workflow_dispatch:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Dependency Review
        uses: actions/dependency-review-action@v2
        with:
          package-ecosystem: "npm"
          directory: "/"
          schedule-interval: "weekly"
          assignees: "protocol-galileo"